version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  db-user:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/user/init.sql:/docker-entrypoint-initdb.d/init.sql

  db-chat:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./db/chat/init.sql:/docker-entrypoint-initdb.d/init.sql

  async-ms-connection:
    build: ./async-ms-connection
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db-user
      - rabbitmq

  async-ms-chat:
    build: ./async-ms-chat
    restart: unless-stopped
    ports:
      - "9086:9086"
    depends_on:
      - db-chat
      - rabbitmq
      - async-ms-connection
